import { expect, test } from '@playwright/test';

test('recovers a lost approval acknowledgement and reloads delivery history without SSE or a progress panel', async ({ page }) => {
  const before = (await (await page.request.get('/api/v1/submissions/history')).json()).items;
  const existingIds = new Set(before.map((record: any) => record.submissionId));
  await page.route('**/api/v1/review-operations/events', (route) => route.abort());
  await page.goto('/review/E006');
  const row = page.locator('.task-table .ant-table-tbody tr').filter({ hasText: 'E2E-测试产品A' });
  await row.locator('a[href^="/task/"]').first().click();
  await page.getByRole('button', { name: '当前目录全选' }).click();
  let requestBody: any;
  let key = '';
  let operationId = '';
  let approveUrl = '';
  await page.route('**/api/v1/tasks/*/approve', async (route) => {
    requestBody = route.request().postDataJSON();
    key = route.request().headers()['idempotency-key']!;
    approveUrl = route.request().url();
    const response = await route.fetch();
    expect(response.status()).toBe(202);
    operationId = (await response.json()).operation.operationId;
    await route.abort('connectionfailed');
  });
  await page.getByRole('button', { name: '审核通过' }).click();
  await page.getByRole('button', { name: '审核并投递' }).click();
  await expect.poll(() => operationId).not.toBe('');
  await page.unroute('**/api/v1/tasks/*/approve');
  await page.reload();
  await page.goto('/history');
  const replay = await page.request.post(approveUrl, { headers: { Prefer: 'respond-async', 'Idempotency-Key': key }, data: requestBody });
  expect(replay.status()).toBe(202);
  expect((await replay.json()).operation.operationId).toBe(operationId);
  await expect.poll(async () => (await (await page.request.get('/api/v1/review-operations/' + operationId)).json()).status).toBe('SUCCEEDED');
  await page.reload();
  await expect(page.getByTestId('review-operation')).toHaveCount(0);
  await expect(page.getByText('审核与投递进度', { exact: true })).toHaveCount(0);
  const pending = (await (await page.request.get('/api/v1/pending-submissions')).json()).items;
  expect(pending.filter((row: any) => row.sourceFolderName === 'E2E-测试产品A')).toEqual([]);
  const history = (await (await page.request.get('/api/v1/submissions/history')).json()).items;
  const delivered = history.filter((record: any) => record.sourceFolder.includes('E2E-测试产品A') && !existingIds.has(record.submissionId));
  expect(delivered).toHaveLength(1);
  await expect(page.locator('.ant-table-row').filter({ hasText: delivered[0].submissionId })).toContainText('投递成功');
});
